# https://console.aws.amazon.com/cloudformation/home?#/stacks/create/review?templateURL=https://content.itoc.com.au.s3-ap-southeast-2.amazonaws.com/aws-roles/github_oidc.yml&stackName=ItocGitHubOIDCAccess

Parameters:
  GithubOrg:
    Type: String
    Description: Github Organisation or Github User Name (example - customerorg)
    Default: customerorg
  RepoName:
    Type: String
    Description: Github Repository name, (example - customer-foundation)
    Default: customer-foundation

Metadata:
  AWS::CloudFormation::Interface: # Enforce Parameter Ordering, and Labels
    ParameterGroups:
      - Label:
          default: Github Details
        Parameters:
          - GithubOrg
          - RepoName

Resources:
  GitHubReadOnlyRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Foundation-ReadOnly
      ManagedPolicyArns: [arn:aws:iam::aws:policy/ReadOnlyAccess]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Ref GithubOidc
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GithubOrg}/${RepoName}:*
  GitHubAdminRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Foundation-Write
      ManagedPolicyArns: [arn:aws:iam::aws:policy/AdministratorAccess]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Ref GithubOidc
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GithubOrg}/${RepoName}:*
  GithubOidc:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ThumbprintList: [6938fd4d98bab03faadb97b34396831e3780aea1]
      ClientIdList:
        - sts.amazonaws.com

Outputs:
  GitHubReadOnlyRole:
    Value: !GetAtt GitHubReadOnlyRole.Arn
  GitHubAdminRole:
    Value: !GetAtt GitHubAdminRole.Arn
