name: Lint Syntax Sec Checks

on:
  workflow_call:

jobs:
  lint_syntax_sec_check:
    name: Run Lint Syntax & Security Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Lint checks
        run: ./deploy/lint_check.sh
      - name: Syntax checks
        run: ./deploy/syntax_check.sh
      - name: Security checks
        run: ./deploy/security_check.sh
